---
- when: "hostvars[host].get('boot_docker_image', False)"
  delegate_to: localhost
  block:
    - name: Create containers
      docker_container:
        name: '{{ boot_docker_host|default(host) }}'
        hostname: '{{ boot_docker_host|default(host) }}'
        command: '{{ hostvars[host]["boot_docker_command"]|default(omit) }}'
        image: '{{ hostvars[host]["boot_docker_image"] }}'
        networks:
          - name: "{{ boot_docker_network|default(omit) }}"
            ipv4_address: "{{ boot_docker_network_ipv4|default(omit) }}"
            ipv6_address: "{{ boot_docker_network_ipv6|default(omit) }}"
            aliases: "{{ boot_docker_network_aliases|default([]) }}"
        purge_networks: "{{ boot_docker_purge_networks|default(true) }}"
        # These are non privileged containers running systemctl, see:
        # https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/
        security_opts: seccomp=unconfined  # required on Debian
        tmpfs:
          - /tmp
          - /run
          - /run/lock
        volumes: '{{ hostvars[host]["boot_docker_volumes"]|default([])
        + ["/sys/fs/cgroup:/sys/fs/cgroup:ro"] }}'
        ports: '{{ hostvars[host]["boot_docker_ports"]|default(omit) }}'

    - name: update inventory
      add_host:
        name: '{{ host }}'
        ansible_host: '{{ boot_docker_host|default(host) }}'
        groups: '{{ hostvars[host]["group_names"] }}'
        ansible_connection: docker
        ansible_user: root
        inventory_dir: "{{ hostvars[host]['inventory_dir'] }}"
      changed_when: false
