---

- name: Create project network
  docker_network:
    name: "{{ project_docker_network }}"
    appends: true
  run_once: true
  delegate_to: localhost
  when:
    - project_docker_network is defined
    - groups["all"]|select('match', '^.+\.lxc$')|list|count

- include_tasks: create_containers.yml
  with_items: '{{ groups["all"] }}'
  loop_control:
    loop_var: host
  run_once: yes
