---

- name: Create project network
  docker_network:
    name: "{{ boot_docker_network }}"
    appends: true
  run_once: true
  delegate_to: localhost
  when:
    - boot_docker_network is defined
    - groups['all']|map('extract', hostvars, 'boot_docker_image')|select('defined')|list|length

- include_tasks: create_containers.yml
  with_items: '{{ groups["all"] }}'
  loop_control:
    loop_var: host
  run_once: yes
