---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    ansible_connection_options:
      connection: local
lint:
  name: yamllint
  enabled: true
platforms:
  - name: delegated-localhost
provisioner:
  name: ansible
  options:
    vvv: true
  inventory:
    host_vars:
      delegated-localhost:
        ansible_connection: local
  lint:
    name: ansible-lint
    enabled: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
