---
- name: Create inventory
  hosts: all
  pre_tasks:
    - name: update inventory (delegated-localhost)
      add_host:
        name: delegated-localhost
      changed_when: false
    - name: update inventory (add container1)
      add_host:
        name: container1
        boot_docker_image: alpine
        boot_docker_command: tail -F /dev/null
        boot_docker_ports:
          - 8080:80
        boot_docker_volumes:
          - /tmp:/tmp/host_tmp:ro
      changed_when: false
    - name: update inventory (add container2)
      add_host:
        name: container2
        boot_docker_image: alpine
        boot_docker_command: tail -F /dev/null
        boot_docker_network_aliases:
          - container2.test
          - app2
      changed_when: false
    - name: update inventory (add container3)
      add_host:
        name: container3
        boot_docker_image: alpine
        boot_docker_command: tail -F /dev/null
        boot_docker_network_aliases:
          - container3.test
          - app3
      changed_when: false

    - name: update inventory (add anotherhost)
      add_host:
        name: anotherhost
      changed_when: false

- name: Converge
  hosts: all
  gather_facts: false
  roles:
    - role: ansible-boot-docker
      vars:
        boot_docker_network: ansible-boot-docker-net
        boot_docker_host: '{{ inventory_hostname }}-test'
