---
- name: Update inventory
  hosts: delegated-localhost
  gather_facts: false
  pre_tasks:
    - name: update inventory
      add_host:
        name: '{{ item }}'
      changed_when: false
      with_items:
        - container1
        - container2
        - container3
        - anotherhost

- name: Converge
  hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: ansible-boot-docker
      delegate_to: localhost
      vars:
        network: ansible-boot-docker-net
        boot_docker_host: '{{ inventory_hostname }}-test'
